CREATE TABLE `ai_scans` (
	`id` int AUTO_INCREMENT NOT NULL,
	`reportToken` varchar(64) NOT NULL,
	`tier` enum('free','growth','elite') NOT NULL,
	`leadId` int,
	`fullName` varchar(200) NOT NULL,
	`email` varchar(320) NOT NULL,
	`company` varchar(200),
	`locale` varchar(8) NOT NULL DEFAULT 'en',
	`responses` text NOT NULL,
	`status` enum('pending','scoring','ready','failed') NOT NULL DEFAULT 'pending',
	`reportPayload` text,
	`overallScore` int,
	`errorMessage` text,
	`utmSource` varchar(120),
	`utmCampaign` varchar(120),
	`ip` varchar(64),
	`userAgent` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`scoredAt` timestamp,
	CONSTRAINT `ai_scans_id` PRIMARY KEY(`id`),
	CONSTRAINT `ai_scans_reportToken_unique` UNIQUE(`reportToken`)
);
