/*
 * IO SKY — Notification Event Catalogue.
 *
 * Generated from "IO_SKY_Notification_Event_Catalogue_v1.0.pdf" (113 pages,
 * 84 events across 9 families) and governed by
 * "IO_SKY_Notification_Center_Functional_Specification.pdf".
 *
 * This module is DATA ONLY. It declares what each notification event is, who
 * may receive it, how it is delivered and how it is deduplicated. It performs
 * no authorisation itself — Functional Specification §37 requires routing and
 * filtering to be enforced server-side, and §3 requires that a notification
 * never grants access to its underlying resource. Consumers must re-check
 * authorisation when the recipient opens the deep link.
 *
 * Priority in the source document is sometimes conditional ("P2/P3 depending
 * on deadline"). The spec text is preserved verbatim in `priority`;
 * `priorityFloor` carries the most urgent level that string can resolve to,
 * so ordering (§36) has something deterministic to sort on.
 */

/** Functional Specification §9 — the nine event families. */
export const NOTIFICATION_FAMILIES = [
  "discovery_calls",
  "ai_scans",
  "clients_accounts",
  "projects_delivery",
  "payments_billing",
  "ai_operations",
  "platform_integrations",
  "security_access",
  "governance_system",
] as const;
export type NotificationFamily = (typeof NOTIFICATION_FAMILIES)[number];

export type NotificationPriority = "P1" | "P2" | "P3" | "P4";

export interface NotificationEvent {
  /** Catalogue identifier, e.g. "AS-05". */
  readonly id: string;
  /** Stable machine name, e.g. "AI_SCAN_READY_FOR_REVIEW". */
  readonly name: string;
  readonly family: NotificationFamily;
  /** NOTIFY, or audit-only where the catalogue says so. */
  readonly classification: string;
  readonly trigger: string;
  /** Prose from the catalogue. Never evaluate this at runtime — see §37. */
  readonly recipients: string;
  readonly permissionScope: string;
  readonly environment: string;
  readonly clientFacing: string;
  /** ACTION_REQUIRED, INFORMATIONAL, RESOLUTION_NOTICE, and similar. */
  readonly actionType: string;
  /** Verbatim spec text, which may be conditional. */
  readonly priority: string;
  /** Most urgent level `priority` can resolve to. */
  readonly priorityFloor: NotificationPriority;
  /** Whether the event appears in the in-app Notification Center. */
  readonly inApp: boolean;
  readonly emailDelivery: string;
  readonly quietHours: string;
  readonly digest: string;
  readonly escalation: string;
  readonly resolution: string;
  /** Composite key used to suppress duplicates (§35). */
  readonly deduplication: string;
  readonly deepLink: string;
  readonly sensitiveContent: string;
  readonly auditRelation: string;
  readonly implementationNotes?: string;
}

export const NOTIFICATION_EVENTS = [

  // ---- Family 1 — Discovery Calls (10 events) ----
  {
    id: "DC-01",
    name: "DISCOVERY_CALL_REQUESTED",
    family: "discovery_calls",
    classification: "NOTIFY",
    trigger: "New valid Discovery Call request created.",
    recipients: "Super Admin; Admin with effective Discovery Call permission and relevant responsibility/assignment.",
    permissionScope: "Effective permission/scope/assignment as specified",
    environment: "Where relevant",
    clientFacing: "Unauthenticated prospect does not require an in-app object; external confirmation uses approved scheduling/transactional channel.",
    actionType: "ACTION_REQUIRED",
    priority: "P3",
    priorityFloor: "P3",
    inApp: true,
    emailDelivery: "IMMEDIATE",
    quietHours: "RESPECT",
    digest: "NO",
    escalation: "If request remains unassigned/unhandled beyond an approved configurable operational threshold.",
    resolution: "Request handled, scheduled, cancelled or otherwise closed.",
    deduplication: "Discovery Call request ID + recipient",
    deepLink: "Authorised Discovery Call record",
    sensitiveContent: "Minimal prospect/company context only.",
    auditRelation: "As applicable",
  },
  {
    id: "DC-02",
    name: "DISCOVERY_CALL_SCHEDULED",
    family: "discovery_calls",
    classification: "NOTIFY",
    trigger: "Discovery Call receives a confirmed scheduled date/time.",
    recipients: "Current assigned responsible internal user; authenticated Client where applicable; external prospect via approved transactional scheduling channel.",
    permissionScope: "Effective permission/scope/assignment as specified",
    environment: "Where relevant",
    clientFacing: "Yes where authenticated; external prospect via approved transactional channel.",
    actionType: "PREPARATION_REQUIRED",
    priority: "P3",
    priorityFloor: "P3",
    inApp: true,
    emailDelivery: "MANDATORY",
    quietHours: "RESPECT",
    digest: "NO",
    escalation: "None unless explicitly stated",
    resolution: "Call cancelled, completed or rescheduled.",
    deduplication: "Call ID + scheduled occurrence + recipient",
    deepLink: "Authorised Discovery Call record",
    sensitiveContent: "Minimal context; no secrets or unauthorised details",
    auditRelation: "As applicable",
  },
  {
    id: "DC-03",
    name: "DISCOVERY_CALL_RESCHEDULED",
    family: "discovery_calls",
    classification: "NOTIFY",
    trigger: "Confirmed scheduled date/time changes.",
    recipients: "Current assigned responsible user(s) and relevant authenticated/external participant.",
    permissionScope: "Effective permission/scope/assignment as specified",
    environment: "Where relevant",
    clientFacing: "Yes where relevant.",
    actionType: "AWARENESS / PREPARATION_REQUIRED",
    priority: "P2 when close to original/new time; otherwise P3",
    priorityFloor: "P2",
    inApp: true,
    emailDelivery: "IMMEDIATE",
    quietHours: "RESPECT",
    digest: "NO",
    escalation: "None unless explicitly stated",
    resolution: "New schedule becomes authoritative.",
    deduplication: "Call ID + reschedule version + recipient",
    deepLink: "Relevant authorised resource",
    sensitiveContent: "Minimal context; no secrets or unauthorised details",
    auditRelation: "As applicable",
    implementationNotes: "All reminders belonging to the old scheduled time must be cancelled/superseded.",
  },
  {
    id: "DC-04",
    name: "DISCOVERY_CALL_CANCELLED",
    family: "discovery_calls",
    classification: "NOTIFY",
    trigger: "Scheduled Discovery Call is cancelled.",
    recipients: "Current responsible users and relevant participant.",
    permissionScope: "Effective permission/scope/assignment as specified",
    environment: "Where relevant",
    clientFacing: "Yes where relevant.",
    actionType: "AWARENESS",
    priority: "P3",
    priorityFloor: "P3",
    inApp: true,
    emailDelivery: "IMMEDIATE",
    quietHours: "RESPECT",
    digest: "NO",
    escalation: "None unless explicitly stated",
    resolution: "Cancellation is final unless Call is explicitly reopened/rebooked.",
    deduplication: "Event ID + resource + recipient + lifecycle occurrence",
    deepLink: "Relevant authorised resource",
    sensitiveContent: "Minimal context; no secrets or unauthorised details",
    auditRelation: "As applicable",
    implementationNotes: "All future 24h and 1h reminders must be cancelled.",
  },
  {
    id: "DC-05",
    name: "DISCOVERY_CALL_UPCOMING_24H",
    family: "discovery_calls",
    classification: "NOTIFY",
    trigger: "24 hours before authoritative scheduled start, only while Call remains active.",
    recipients: "Current assigned authorised internal responsible user.",
    permissionScope: "Effective permission/scope/assignment as specified",
    environment: "Where relevant",
    clientFacing: "No unless explicitly stated",
    actionType: "PREPARATION_REQUIRED",
    priority: "P3",
    priorityFloor: "P3",
    inApp: true,
    emailDelivery: "IMMEDIATE",
    quietHours: "RESPECT",
    digest: "NO",
    escalation: "None unless explicitly stated",
    resolution: "Call cancelled, rescheduled, completed, or 1h reminder becomes the current imminent reminder.",
    deduplication: "Call ID + scheduled occurrence + 24H + recipient",
    deepLink: "Discovery Call with intake/prospect context",
    sensitiveContent: "Minimal context; no secrets or unauthorised details",
    auditRelation: "As applicable",
    implementationNotes: "Generate only if Call remains scheduled, recipient remains assigned and recipient remains authorised.",
  },
  {
    id: "DC-06",
    name: "DISCOVERY_CALL_UPCOMING_1H",
    family: "discovery_calls",
    classification: "NOTIFY",
    trigger: "One hour before authoritative scheduled start, only while Call remains active.",
    recipients: "Current assigned authorised responsible user.",
    permissionScope: "Effective permission/scope/assignment as specified",
    environment: "Where relevant",
    clientFacing: "No unless explicitly stated",
    actionType: "PREPARATION_REQUIRED",
    priority: "P2",
    priorityFloor: "P2",
    inApp: true,
    emailDelivery: "IMMEDIATE",
    quietHours: "RESPECT",
    digest: "NO",
    escalation: "None unless explicitly stated",
    resolution: "Call starts/completes/cancels/reschedules.",
    deduplication: "Call ID + scheduled occurrence + 1H + recipient",
    deepLink: "Relevant authorised resource",
    sensitiveContent: "Minimal context; no secrets or unauthorised details",
    auditRelation: "As applicable",
  },
  {
    id: "DC-07",
    name: "DISCOVERY_CALL_RETRY_DUE",
    family: "discovery_calls",
    classification: "NOTIFY",
    trigger: "Explicit retry/next-attempt timestamp is reached.",
    recipients: "Current assigned responsible user.",
    permissionScope: "Effective permission/scope/assignment as specified",
    environment: "Where relevant",
    clientFacing: "No unless explicitly stated",
    actionType: "ACTION_REQUIRED",
    priority: "P2/P3 based on urgency",
    priorityFloor: "P2",
    inApp: true,
    emailDelivery: "IMMEDIATE for P2; OPTIONAL for P3",
    quietHours: "RESPECT",
    digest: "NO",
    escalation: "Based on configured next-action policy if repeatedly unhandled.",
    resolution: "Retry completed, cancelled or superseded by new follow-up.",
    deduplication: "Call ID + retry timestamp/version + recipient",
    deepLink: "Relevant authorised resource",
    sensitiveContent: "Minimal context; no secrets or unauthorised details",
    auditRelation: "As applicable",
    implementationNotes: "No arbitrary retry schedule may be invented; this follows an explicit business retry timestamp.",
  },
  {
    id: "DC-08",
    name: "DISCOVERY_CALL_FOLLOW_UP_DUE",
    family: "discovery_calls",
    classification: "NOTIFY",
    trigger: "Explicit follow-up/next-action deadline is reached.",
    recipients: "Assigned responsible user.",
    permissionScope: "Effective permission/scope/assignment as specified",
    environment: "Where relevant",
    clientFacing: "No unless explicitly stated",
    actionType: "ACTION_REQUIRED",
    priority: "P2/P3",
    priorityFloor: "P2",
    inApp: true,
    emailDelivery: "IMMEDIATE",
    quietHours: "RESPECT",
    digest: "NO",
    escalation: "None unless explicitly stated",
    resolution: "Follow-up completed, cancelled or superseded.",
    deduplication: "Call ID + follow-up occurrence + recipient",
    deepLink: "Discovery Call/prospect record",
    sensitiveContent: "Minimal context; no secrets or unauthorised details",
    auditRelation: "As applicable",
  },
  {
    id: "DC-09",
    name: "DISCOVERY_CALL_INFORMATION_UPDATED",
    family: "discovery_calls",
    classification: "NOTIFY",
    trigger: "Material new prospect/Client information relevant to an upcoming or active Call is added or changed.",
    recipients: "Current responsible user(s).",
    permissionScope: "Effective permission/scope/assignment as specified",
    environment: "Where relevant",
    clientFacing: "No unless explicitly stated",
    actionType: "AWARENESS / PREPARATION_REQUIRED",
    priority: "P3",
    priorityFloor: "P3",
    inApp: true,
    emailDelivery: "OPTIONAL",
    quietHours: "RESPECT",
    digest: "YES",
    escalation: "None unless explicitly stated",
    resolution: "Informational; no persistent action state unless underlying action is separately created.",
    deduplication: "Event ID + resource + recipient + lifecycle occurrence",
    deepLink: "Relevant authorised resource",
    sensitiveContent: "Minimal context; no secrets or unauthorised details",
    auditRelation: "As applicable",
    implementationNotes: "Do not generate for trivial field edits, formatting changes or autosave.",
  },
  {
    id: "DC-10",
    name: "DISCOVERY_CALL_ACTION_REQUIRED",
    family: "discovery_calls",
    classification: "NOTIFY",
    trigger: "A genuine Discovery Call action exists and no more specific Discovery Call event applies.",
    recipients: "Clearly responsible authorised user(s).",
    permissionScope: "Effective permission/scope/assignment as specified",
    environment: "Where relevant",
    clientFacing: "No unless explicitly stated",
    actionType: "ACTION_REQUIRED",
    priority: "P2/P3",
    priorityFloor: "P2",
    inApp: true,
    emailDelivery: "IMMEDIATE where time-sensitive",
    quietHours: "RESPECT",
    digest: "NO",
    escalation: "None unless explicitly stated",
    resolution: "Underlying action completed/cancelled/superseded.",
    deduplication: "Event ID + resource + recipient + lifecycle occurrence",
    deepLink: "Relevant authorised resource",
    sensitiveContent: "Minimal context; no secrets or unauthorised details",
    auditRelation: "As applicable",
    implementationNotes: "Restricted fallback only; must never become a generic dumping ground.",
  },

  // ---- Family 2 — AI Scans (13 events) ----
  {
    id: "AS-01",
    name: "AI_SCAN_CREATED",
    family: "ai_scans",
    classification: "NOTIFY",
    trigger: "Valid Scan instance is created/purchased.",
    recipients: "Relevant authorised AI Scan Operations user(s) where operational awareness is required.",
    permissionScope: "Effective permission/scope/assignment as specified",
    environment: "Where relevant",
    clientFacing: "Client may receive purchase confirmation through appropriate Client-facing channel.",
    actionType: "AWARENESS",
    priority: "P3",
    priorityFloor: "P3",
    inApp: true,
    emailDelivery: "OPTIONAL internally; Client purchase confirmation transactional as appropriate",
    quietHours: "RESPECT",
    digest: "YES internally where no action is required",
    escalation: "None unless explicitly stated",
    resolution: "Scan progresses or is otherwise closed.",
    deduplication: "Event ID + resource + recipient + lifecycle occurrence",
    deepLink: "Relevant authorised resource",
    sensitiveContent: "Minimal context; no secrets or unauthorised details",
    auditRelation: "As applicable",
  },
  {
    id: "AS-02",
    name: "AI_SCAN_INFORMATION_REQUIRED",
    family: "ai_scans",
    classification: "NOTIFY",
    trigger: "Required Client input is missing and Scan progress is blocked or cannot correctly continue.",
    recipients: "Correct Client; authorised assigned Scan Operations responsible user(s).",
    permissionScope: "Effective permission/scope/assignment as specified",
    environment: "Where relevant",
    clientFacing: "Yes - only describe what the Client needs to provide.",
    actionType: "ACTION_REQUIRED",
    priority: "P2",
    priorityFloor: "P2",
    inApp: true,
    emailDelivery: "IMMEDIATE",
    quietHours: "RESPECT",
    digest: "NO",
    escalation: "If information remains outstanding and delivery window is threatened, escalate internally to responsible Scan Operations + Super Admin.",
    resolution: "Required information supplied or requirement explicitly cancelled.",
    deduplication: "Event ID + resource + recipient + lifecycle occurrence",
    deepLink: "Client Scan input/request view or internal Scan operations view",
    sensitiveContent: "Minimal context; no secrets or unauthorised details",
    auditRelation: "As applicable",
  },
  {
    id: "AS-03",
    name: "AI_SCAN_SUBMITTED",
    family: "ai_scans",
    classification: "NOTIFY",
    trigger: "Client successfully submits completed assessment.",
    recipients: "Assigned authorised Scan Operations users; Super Admin where appropriate for oversight.",
    permissionScope: "Effective permission/scope/assignment as specified",
    environment: "Where relevant",
    clientFacing: "Yes - submission confirmation.",
    actionType: "AWARENESS",
    priority: "P3",
    priorityFloor: "P3",
    inApp: true,
    emailDelivery: "Client confirmation MANDATORY/transactional; internal OPTIONAL",
    quietHours: "RESPECT",
    digest: "YES internally where no immediate action is required",
    escalation: "None unless explicitly stated",
    resolution: "Analysis begins/progresses.",
    deduplication: "Event ID + resource + recipient + lifecycle occurrence",
    deepLink: "Relevant authorised resource",
    sensitiveContent: "Minimal context; no secrets or unauthorised details",
    auditRelation: "As applicable",
  },
  {
    id: "AS-04",
    name: "AI_SCAN_ANALYSIS_EXCEPTION",
    family: "ai_scans",
    classification: "NOTIFY",
    trigger: "Analysis materially fails/cannot continue and requires human intervention.",
    recipients: "Authorised Scan Operations responsible user; relevant authorised technical operator where technically assigned; Super Admin when impact is material.",
    permissionScope: "Effective permission/scope/assignment as specified",
    environment: "Where relevant",
    clientFacing: "No internal technical detail.",
    actionType: "ACTION_REQUIRED",
    priority: "P1/P2",
    priorityFloor: "P1",
    inApp: true,
    emailDelivery: "IMMEDIATE",
    quietHours: "P1 BYPASS; P2 RESPECT unless business-critical",
    digest: "NO",
    escalation: "Escalate to Super Admin when unresolved and Scan delivery becomes at risk.",
    resolution: "Analysis successfully resumes/completes or Scan is operationally closed.",
    deduplication: "Event ID + resource + recipient + lifecycle occurrence",
    deepLink: "Relevant authorised resource",
    sensitiveContent: "No substantive findings, secrets or unnecessary technical internals.",
    auditRelation: "As applicable",
  },
  {
    id: "AS-05",
    name: "AI_SCAN_READY_FOR_REVIEW",
    family: "ai_scans",
    classification: "NOTIFY",
    trigger: "Analysis successfully completes and reviewable report output is available.",
    recipients: "Super Admin; Admin explicitly authorised with scan.review and access/assignment; Developer only when explicitly assigned as Reviewer for this specific Scan and given required review authorization.",
    permissionScope: "Effective permission/scope/assignment as specified",
    environment: "Where relevant",
    clientFacing: "No. Never Client-visible before authorised publication.",
    actionType: "ACTION_REQUIRED",
    priority: "P2",
    priorityFloor: "P2",
    inApp: true,
    emailDelivery: "IMMEDIATE",
    quietHours: "RESPECT",
    digest: "NO",
    escalation: "Deadline-aware; AI_SCAN_DELIVERY_AT_RISK when configured delivery window is threatened.",
    resolution: "Review completed; reviewer reassigned where old reviewer is no longer responsible; Scan returned to analysis/correction; or Scan cancelled/superseded.",
    deduplication: "Scan ID + review lifecycle version + recipient",
    deepLink: "Internal Scan Review Workspace",
    sensitiveContent: "Preview must not contain substantive findings.",
    auditRelation: "As applicable",
    implementationNotes: "Ordinary Developer, Technical Operator and Client are not recipients merely by role.",
  },
  {
    id: "AS-06",
    name: "AI_SCAN_REVIEW_ASSIGNED",
    family: "ai_scans",
    classification: "NOTIFY",
    trigger: "Specific reviewer is assigned or reassigned to a Scan.",
    recipients: "Newly assigned authorised Reviewer.",
    permissionScope: "Effective permission/scope/assignment as specified",
    environment: "Where relevant",
    clientFacing: "No unless explicitly stated",
    actionType: "ACTION_REQUIRED",
    priority: "P2",
    priorityFloor: "P2",
    inApp: true,
    emailDelivery: "IMMEDIATE",
    quietHours: "RESPECT",
    digest: "NO",
    escalation: "None unless explicitly stated",
    resolution: "Review completed, reassigned or cancelled.",
    deduplication: "Scan ID + assignment version + reviewer",
    deepLink: "Assigned Scan Review Workspace",
    sensitiveContent: "Minimal context; no secrets or unauthorised details",
    auditRelation: "As applicable",
    implementationNotes: "Reviewer assignment must not provide access to unrelated Scans.",
  },
  {
    id: "AS-07",
    name: "AI_SCAN_REVIEW_REMINDER",
    family: "ai_scans",
    classification: "NOTIFY",
    trigger: "Review remains unresolved and an approved deadline-based reminder point is reached.",
    recipients: "Current assigned Reviewer.",
    permissionScope: "Effective permission/scope/assignment as specified",
    environment: "Where relevant",
    clientFacing: "No unless explicitly stated",
    actionType: "ACTION_REQUIRED",
    priority: "P2",
    priorityFloor: "P2",
    inApp: true,
    emailDelivery: "IMMEDIATE",
    quietHours: "RESPECT",
    digest: "NO",
    escalation: "If delivery risk threshold is reached, generate AI_SCAN_DELIVERY_AT_RISK.",
    resolution: "Review completed/reassigned/cancelled/superseded.",
    deduplication: "Scan ID + reminder threshold + current reviewer",
    deepLink: "Relevant authorised resource",
    sensitiveContent: "Minimal context; no secrets or unauthorised details",
    auditRelation: "As applicable",
  },
  {
    id: "AS-08",
    name: "AI_SCAN_CHANGES_REQUIRED",
    family: "ai_scans",
    classification: "NOTIFY",
    trigger: "Reviewer explicitly determines output requires correction/reprocessing before approval.",
    recipients: "Appropriate authorised person/team responsible for correction or analysis.",
    permissionScope: "Effective permission/scope/assignment as specified",
    environment: "Where relevant",
    clientFacing: "No.",
    actionType: "ACTION_REQUIRED",
    priority: "P2",
    priorityFloor: "P2",
    inApp: true,
    emailDelivery: "IMMEDIATE",
    quietHours: "RESPECT",
    digest: "NO",
    escalation: "None unless explicitly stated",
    resolution: "Revised version becomes available for review.",
    deduplication: "Event ID + resource + recipient + lifecycle occurrence",
    deepLink: "Relevant authorised resource",
    sensitiveContent: "Minimal context; no secrets or unauthorised details",
    auditRelation: "Review decision must be traceable.",
  },
  {
    id: "AS-09",
    name: "AI_SCAN_REVIEW_APPROVED",
    family: "ai_scans",
    classification: "NOTIFY",
    trigger: "Authorised Reviewer clicks Approve; reviewed report version enters Approved / Ready for Publication state.",
    recipients: "Super Admin; Admin with explicit scan.publish permission AND access to that Scan.",
    permissionScope: "Effective permission/scope/assignment as specified",
    environment: "Where relevant",
    clientFacing: "No until publication succeeds.",
    actionType: "ACTION_REQUIRED",
    priority: "P2",
    priorityFloor: "P2",
    inApp: true,
    emailDelivery: "IMMEDIATE",
    quietHours: "RESPECT",
    digest: "NO",
    escalation: "None unless explicitly stated",
    resolution: "Successfully published; approval revoked through authorised correction workflow; or Scan superseded.",
    deduplication: "Scan ID + approved report version + publisher recipient",
    deepLink: "Approved Scan / Publish Workspace",
    sensitiveContent: "Minimal context; no secrets or unauthorised details",
    auditRelation: "Approval event must be traceable.",
    implementationNotes: "Notification context should minimally show Client, Scan type, Approved status, reviewer identity, approval timestamp, report language and approved version identifier. Reviewer authority alone does not grant Publish.",
  },
  {
    id: "AS-10",
    name: "AI_SCAN_PUBLICATION_FAILED",
    family: "ai_scans",
    classification: "NOTIFY",
    trigger: "Authorised Publish attempt fails before the correct approved report has become successfully available in the correct Client Portal.",
    recipients: "Attempting Publisher; Super Admin.",
    permissionScope: "Effective permission/scope/assignment as specified",
    environment: "Where relevant",
    clientFacing: "No notification.",
    actionType: "ACTION_REQUIRED",
    priority: "P1/P2 depending on delivery impact",
    priorityFloor: "P1",
    inApp: true,
    emailDelivery: "IMMEDIATE",
    quietHours: "P1 BYPASS; P2 RESPECT",
    digest: "NO",
    escalation: "P1 immediate; P2 according to delivery risk.",
    resolution: "Successful publication or deliberate authorised operational resolution.",
    deduplication: "Scan ID + publication failure lifecycle; technical retries must not flood users.",
    deepLink: "Relevant authorised resource",
    sensitiveContent: "Minimal context; no secrets or unauthorised details",
    auditRelation: "Failed privileged publication attempt must be traceable.",
    implementationNotes: "The system must not produce AI_SCAN_PUBLISHED or a Client availability notification unless publication success has been verified.",
  },
  {
    id: "AS-11",
    name: "AI_SCAN_PUBLISHED",
    family: "ai_scans",
    classification: "NOTIFY",
    trigger: "Authorised publication completed successfully and correct approved report is available in correct Client Portal.",
    recipients: "Correct Client; relevant authorised internal users where useful.",
    permissionScope: "Effective permission/scope/assignment as specified",
    environment: "Where relevant",
    clientFacing: "Yes.",
    actionType: "AWARENESS / View report",
    priority: "P3",
    priorityFloor: "P3",
    inApp: true,
    emailDelivery: "IMMEDIATE to Client",
    quietHours: "RESPECT",
    digest: "NO",
    escalation: "None unless explicitly stated",
    resolution: "Informational availability event; report remains available according to portal lifecycle.",
    deduplication: "Scan ID + published approved version + recipient",
    deepLink: "Correct published Client Portal report",
    sensitiveContent: "Minimal context; no secrets or unauthorised details",
    auditRelation: "Publisher, timestamp, version, Client and publication state must be traceable.",
    implementationNotes: "Client receives only the published version. Client-facing notification uses configured Client language where supported.",
  },
  {
    id: "AS-12",
    name: "AI_SCAN_DELIVERY_AT_RISK",
    family: "ai_scans",
    classification: "NOTIFY",
    trigger: "Remaining configured delivery time is materially threatened while required review, approval or publication remains outstanding.",
    recipients: "Current responsible reviewer/publisher as applicable; Super Admin.",
    permissionScope: "Effective permission/scope/assignment as specified",
    environment: "Where relevant",
    clientFacing: "No unless explicitly stated",
    actionType: "ACTION_REQUIRED",
    priority: "P2",
    priorityFloor: "P2",
    inApp: true,
    emailDelivery: "IMMEDIATE",
    quietHours: "RESPECT",
    digest: "NO",
    escalation: "This event is itself an escalation state.",
    resolution: "Risk cleared through progression or Scan delivery completed.",
    deduplication: "Scan ID + risk lifecycle/version + recipient",
    deepLink: "Relevant authorised resource",
    sensitiveContent: "Minimal context; no secrets or unauthorised details",
    auditRelation: "As applicable",
  },
  {
    id: "AS-13",
    name: "AI_SCAN_DELIVERY_OVERDUE",
    family: "ai_scans",
    classification: "NOTIFY",
    trigger: "Applicable committed Scan delivery deadline passes while Client-facing delivery remains incomplete.",
    recipients: "Super Admin; current responsible authorised internal user(s).",
    permissionScope: "Effective permission/scope/assignment as specified",
    environment: "Where relevant",
    clientFacing: "No internal workflow details are exposed.",
    actionType: "ACTION_REQUIRED",
    priority: "P1/P2",
    priorityFloor: "P1",
    inApp: true,
    emailDelivery: "IMMEDIATE",
    quietHours: "P1 BYPASS only if severity warrants; otherwise RESPECT",
    digest: "NO",
    escalation: "None unless explicitly stated",
    resolution: "Delivery completed or authorised exception resolved.",
    deduplication: "Event ID + resource + recipient + lifecycle occurrence",
    deepLink: "Relevant authorised resource",
    sensitiveContent: "Minimal context; no secrets or unauthorised details",
    auditRelation: "As applicable",
  },

  // ---- Family 3 — Clients & Accounts (6 events) ----
  {
    id: "CA-01",
    name: "CLIENT_ACCOUNT_CREATED",
    family: "clients_accounts",
    classification: "NOTIFY",
    trigger: "Client account/organisation created and relevant operational awareness is required.",
    recipients: "Assigned authorised Client-management users.",
    permissionScope: "Effective permission/scope/assignment as specified",
    environment: "Where relevant",
    clientFacing: "Client may receive onboarding/account-access communication separately.",
    actionType: "AWARENESS / ACTION_REQUIRED depending on onboarding",
    priority: "P3",
    priorityFloor: "P3",
    inApp: true,
    emailDelivery: "OPTIONAL internally; onboarding communication as required externally",
    quietHours: "RESPECT",
    digest: "YES internally if not action-required",
    escalation: "None unless explicitly stated",
    resolution: "Onboarding/assignment completed or account state superseded.",
    deduplication: "Event ID + resource + recipient + lifecycle occurrence",
    deepLink: "Relevant authorised resource",
    sensitiveContent: "Minimal context; no secrets or unauthorised details",
    auditRelation: "As applicable",
  },
  {
    id: "CA-02",
    name: "CLIENT_INFORMATION_REQUIRED",
    family: "clients_accounts",
    classification: "NOTIFY",
    trigger: "Authorised internal user explicitly requests Client information/documentation.",
    recipients: "Correct Client; assigned responsible internal user where tracking is useful.",
    permissionScope: "Effective permission/scope/assignment as specified",
    environment: "Where relevant",
    clientFacing: "Yes.",
    actionType: "ACTION_REQUIRED for Client",
    priority: "P2/P3",
    priorityFloor: "P2",
    inApp: true,
    emailDelivery: "IMMEDIATE to Client",
    quietHours: "RESPECT",
    digest: "NO",
    escalation: "None unless explicitly stated",
    resolution: "Requested information received or request cancelled/superseded.",
    deduplication: "Event ID + resource + recipient + lifecycle occurrence",
    deepLink: "Relevant authorised resource",
    sensitiveContent: "Minimal context; no secrets or unauthorised details",
    auditRelation: "As applicable",
  },
  {
    id: "CA-03",
    name: "CLIENT_INFORMATION_SUBMITTED",
    family: "clients_accounts",
    classification: "NOTIFY",
    trigger: "Client supplies requested information/documentation.",
    recipients: "Current assigned responsible internal user(s).",
    permissionScope: "Effective permission/scope/assignment as specified",
    environment: "Where relevant",
    clientFacing: "No unless explicitly stated",
    actionType: "ACTION_REQUIRED or AWARENESS depending on workflow",
    priority: "P3",
    priorityFloor: "P3",
    inApp: true,
    emailDelivery: "OPTIONAL; IMMEDIATE where work is blocked awaiting this input",
    quietHours: "RESPECT",
    digest: "YES only if no action is urgent",
    escalation: "None unless explicitly stated",
    resolution: "Underlying request/workflow progresses or is closed.",
    deduplication: "Event ID + resource + recipient + lifecycle occurrence",
    deepLink: "Relevant authorised resource",
    sensitiveContent: "Minimal context; no secrets or unauthorised details",
    auditRelation: "As applicable",
  },
  {
    id: "CA-04",
    name: "CLIENT_MATERIAL_INFORMATION_UPDATED",
    family: "clients_accounts",
    classification: "NOTIFY",
    trigger: "Material Client information changes in a way requiring authorised awareness/action.",
    recipients: "Assigned relevant user(s).",
    permissionScope: "Effective permission/scope/assignment as specified",
    environment: "Where relevant",
    clientFacing: "No unless explicitly stated",
    actionType: "AWARENESS",
    priority: "P3",
    priorityFloor: "P3",
    inApp: true,
    emailDelivery: "OPTIONAL",
    quietHours: "RESPECT",
    digest: "YES",
    escalation: "None unless explicitly stated",
    resolution: "Informational unless a separate action is created.",
    deduplication: "Event ID + resource + recipient + lifecycle occurrence",
    deepLink: "Relevant authorised resource",
    sensitiveContent: "Minimal context; no secrets or unauthorised details",
    auditRelation: "As applicable",
    implementationNotes: "No event for routine profile edits without operational significance.",
  },
  {
    id: "CA-05",
    name: "CLIENT_ACCOUNT_ACTION_REQUIRED",
    family: "clients_accounts",
    classification: "NOTIFY",
    trigger: "Genuine Client-account action exists and no more specific event applies.",
    recipients: "Correct Client and/or assigned authorised internal user dictated by underlying action.",
    permissionScope: "Effective permission/scope/assignment as specified",
    environment: "Where relevant",
    clientFacing: "No unless explicitly stated",
    actionType: "ACTION_REQUIRED",
    priority: "P2/P3",
    priorityFloor: "P2",
    inApp: true,
    emailDelivery: "IMMEDIATE where deadline exists",
    quietHours: "RESPECT",
    digest: "NO when action deadline exists",
    escalation: "None unless explicitly stated",
    resolution: "Underlying action completed/cancelled/superseded.",
    deduplication: "Event ID + resource + recipient + lifecycle occurrence",
    deepLink: "Relevant authorised resource",
    sensitiveContent: "Minimal context; no secrets or unauthorised details",
    auditRelation: "As applicable",
    implementationNotes: "Strict fallback only.",
  },
  {
    id: "CA-06",
    name: "CLIENT_ACCOUNT_SECURITY_ACTION_REQUIRED",
    family: "clients_accounts",
    classification: "NOTIFY",
    trigger: "Client must take account-level security action.",
    recipients: "Affected Client; authorised security oversight only where necessary.",
    permissionScope: "Effective permission/scope/assignment as specified",
    environment: "Where relevant",
    clientFacing: "Yes, but no internal Security Center details.",
    actionType: "ACTION_REQUIRED",
    priority: "P1/P2",
    priorityFloor: "P1",
    inApp: true,
    emailDelivery: "IMMEDIATE",
    quietHours: "P1 BYPASS; otherwise RESPECT",
    digest: "NO",
    escalation: "None unless explicitly stated",
    resolution: "Required security action completed or authorised resolution.",
    deduplication: "Event ID + resource + recipient + lifecycle occurrence",
    deepLink: "Relevant authorised resource",
    sensitiveContent: "Minimal safe Client-facing security context only.",
    auditRelation: "As applicable",
  },

  // ---- Family 4 — Projects & Delivery (17 events) ----
  {
    id: "PD-01",
    name: "PROJECT_ASSIGNED",
    family: "projects_delivery",
    classification: "NOTIFY",
    trigger: "User receives responsibility for Project/resource.",
    recipients: "Newly assigned authorised user.",
    permissionScope: "Effective permission/scope/assignment as specified",
    environment: "Where relevant",
    clientFacing: "No unless explicitly stated",
    actionType: "AWARENESS / ACTION_REQUIRED",
    priority: "P3",
    priorityFloor: "P3",
    inApp: true,
    emailDelivery: "IMMEDIATE",
    quietHours: "RESPECT",
    digest: "NO",
    escalation: "None unless explicitly stated",
    resolution: "Assignment completed, removed or reassigned.",
    deduplication: "Project ID + assignment version + recipient",
    deepLink: "Relevant authorised resource",
    sensitiveContent: "Minimal context; no secrets or unauthorised details",
    auditRelation: "As applicable",
  },
  {
    id: "PD-02",
    name: "PROJECT_REASSIGNED",
    family: "projects_delivery",
    classification: "NOTIFY",
    trigger: "Project responsibility changes.",
    recipients: "New responsible user; previous user only where operational handoff awareness is necessary.",
    permissionScope: "Effective permission/scope/assignment as specified",
    environment: "Where relevant",
    clientFacing: "No unless explicitly stated",
    actionType: "AWARENESS",
    priority: "P3",
    priorityFloor: "P3",
    inApp: true,
    emailDelivery: "IMMEDIATE",
    quietHours: "RESPECT",
    digest: "NO",
    escalation: "None unless explicitly stated",
    resolution: "New assignment becomes authoritative.",
    deduplication: "Event ID + resource + recipient + lifecycle occurrence",
    deepLink: "Relevant authorised resource",
    sensitiveContent: "Minimal context; no secrets or unauthorised details",
    auditRelation: "As applicable",
    implementationNotes: "Future notifications follow current assignment.",
  },
  {
    id: "PD-03",
    name: "PROJECT_MILESTONE_UPDATED",
    family: "projects_delivery",
    classification: "NOTIFY",
    trigger: "Material milestone state/date/scope changes.",
    recipients: "Assigned authorised Project participants whose work/responsibility is affected.",
    permissionScope: "Effective permission/scope/assignment as specified",
    environment: "Where relevant",
    clientFacing: "No unless explicitly stated",
    actionType: "AWARENESS / PREPARATION_REQUIRED",
    priority: "P3",
    priorityFloor: "P3",
    inApp: true,
    emailDelivery: "OPTIONAL",
    quietHours: "RESPECT",
    digest: "YES if not time-critical",
    escalation: "None unless explicitly stated",
    resolution: "Informational or superseded by later milestone state.",
    deduplication: "Event ID + resource + recipient + lifecycle occurrence",
    deepLink: "Relevant authorised resource",
    sensitiveContent: "Minimal context; no secrets or unauthorised details",
    auditRelation: "As applicable",
    implementationNotes: "No event for cosmetic/minor edits.",
  },
  {
    id: "PD-04",
    name: "PROJECT_DEADLINE_7D",
    family: "projects_delivery",
    classification: "NOTIFY",
    trigger: "Active incomplete milestone/deliverable reaches seven days before deadline.",
    recipients: "Responsible Implementer/owner + relevant Project/Delivery Manager.",
    permissionScope: "Effective permission/scope/assignment as specified",
    environment: "Where relevant",
    clientFacing: "No unless explicitly stated",
    actionType: "PREPARATION_REQUIRED",
    priority: "P3",
    priorityFloor: "P3",
    inApp: true,
    emailDelivery: "IMMEDIATE",
    quietHours: "RESPECT",
    digest: "NO",
    escalation: "None unless explicitly stated",
    resolution: "Completed, cancelled or superseded.",
    deduplication: "Project/milestone ID + deadline version + 7D + recipient",
    deepLink: "Relevant authorised resource",
    sensitiveContent: "Minimal context; no secrets or unauthorised details",
    auditRelation: "As applicable",
  },
  {
    id: "PD-05",
    name: "PROJECT_DEADLINE_3D",
    family: "projects_delivery",
    classification: "NOTIFY",
    trigger: "Active incomplete work reaches three days before deadline.",
    recipients: "Current responsible users + appropriate delivery oversight.",
    permissionScope: "Effective permission/scope/assignment as specified",
    environment: "Where relevant",
    clientFacing: "No unless explicitly stated",
    actionType: "ACTION_REQUIRED / PREPARATION_REQUIRED",
    priority: "P2",
    priorityFloor: "P2",
    inApp: true,
    emailDelivery: "IMMEDIATE",
    quietHours: "RESPECT",
    digest: "NO",
    escalation: "None unless explicitly stated",
    resolution: "Completed, cancelled or superseded.",
    deduplication: "Project/milestone ID + deadline version + 3D + recipient",
    deepLink: "Relevant authorised resource",
    sensitiveContent: "Minimal context; no secrets or unauthorised details",
    auditRelation: "As applicable",
  },
  {
    id: "PD-06",
    name: "PROJECT_DEADLINE_24H",
    family: "projects_delivery",
    classification: "NOTIFY",
    trigger: "Active incomplete milestone/deliverable reaches 24 hours before deadline.",
    recipients: "Responsible user + appropriate Project/Delivery oversight.",
    permissionScope: "Effective permission/scope/assignment as specified",
    environment: "Where relevant",
    clientFacing: "No unless explicitly stated",
    actionType: "ACTION_REQUIRED",
    priority: "P2",
    priorityFloor: "P2",
    inApp: true,
    emailDelivery: "IMMEDIATE",
    quietHours: "RESPECT",
    digest: "NO",
    escalation: "None unless explicitly stated",
    resolution: "Completed, cancelled or superseded.",
    deduplication: "Project/milestone ID + deadline version + 24H + recipient",
    deepLink: "Relevant authorised resource",
    sensitiveContent: "Minimal context; no secrets or unauthorised details",
    auditRelation: "As applicable",
    implementationNotes: "This is a final reminder, not the first warning.",
  },
  {
    id: "PD-07",
    name: "PROJECT_DEADLINE_MISSED",
    family: "projects_delivery",
    classification: "NOTIFY",
    trigger: "Deadline passes while required work remains incomplete.",
    recipients: "Assigned responsible user; Project Manager/Delivery Manager with effective authorization; Super Admin where escalation policy requires.",
    permissionScope: "Effective permission/scope/assignment as specified",
    environment: "Where relevant",
    clientFacing: "No unless explicitly stated",
    actionType: "ACTION_REQUIRED",
    priority: "P2",
    priorityFloor: "P2",
    inApp: true,
    emailDelivery: "IMMEDIATE",
    quietHours: "RESPECT",
    digest: "NO",
    escalation: "Escalate according to authorised Project/Delivery responsibility and configured policy.",
    resolution: "Work completed or deadline/status formally superseded.",
    deduplication: "Event ID + resource + recipient + lifecycle occurrence",
    deepLink: "Relevant authorised resource",
    sensitiveContent: "Minimal context; no secrets or unauthorised details",
    auditRelation: "As applicable",
  },
  {
    id: "PD-08",
    name: "PROJECT_REVIEW_REQUESTED",
    family: "projects_delivery",
    classification: "NOTIFY",
    trigger: "Work formally enters Review Requested state.",
    recipients: "Explicitly assigned Reviewer.",
    permissionScope: "Effective permission/scope/assignment as specified",
    environment: "Where relevant",
    clientFacing: "No unless explicitly stated",
    actionType: "ACTION_REQUIRED",
    priority: "P2/P3 depending on deadline",
    priorityFloor: "P2",
    inApp: true,
    emailDelivery: "IMMEDIATE",
    quietHours: "RESPECT",
    digest: "NO",
    escalation: "None unless explicitly stated",
    resolution: "Review completed/reassigned/cancelled.",
    deduplication: "Event ID + resource + recipient + lifecycle occurrence",
    deepLink: "Relevant authorised resource",
    sensitiveContent: "Minimal context; no secrets or unauthorised details",
    auditRelation: "As applicable",
    implementationNotes: "Developer role alone does not trigger review notification; actual Reviewer assignment must exist.",
  },
  {
    id: "PD-09",
    name: "PROJECT_REVIEWER_ASSIGNED",
    family: "projects_delivery",
    classification: "NOTIFY",
    trigger: "Reviewer is assigned/reassigned.",
    recipients: "Newly assigned Reviewer.",
    permissionScope: "Effective permission/scope/assignment as specified",
    environment: "Where relevant",
    clientFacing: "No unless explicitly stated",
    actionType: "ACTION_REQUIRED",
    priority: "P3",
    priorityFloor: "P3",
    inApp: true,
    emailDelivery: "IMMEDIATE",
    quietHours: "RESPECT",
    digest: "NO",
    escalation: "None unless explicitly stated",
    resolution: "Review completed/reassigned.",
    deduplication: "Event ID + resource + recipient + lifecycle occurrence",
    deepLink: "Relevant authorised resource",
    sensitiveContent: "Minimal context; no secrets or unauthorised details",
    auditRelation: "As applicable",
  },
  {
    id: "PD-10",
    name: "PROJECT_IMPLEMENTATION_ACTION_REQUIRED",
    family: "projects_delivery",
    classification: "NOTIFY",
    trigger: "Concrete implementation action is assigned.",
    recipients: "Assigned Implementer.",
    permissionScope: "Effective permission/scope/assignment as specified",
    environment: "Where relevant",
    clientFacing: "No unless explicitly stated",
    actionType: "ACTION_REQUIRED",
    priority: "P2/P3",
    priorityFloor: "P2",
    inApp: true,
    emailDelivery: "IMMEDIATE where deadline/action is material",
    quietHours: "RESPECT",
    digest: "NO",
    escalation: "None unless explicitly stated",
    resolution: "Action completed/cancelled/superseded.",
    deduplication: "Event ID + resource + recipient + lifecycle occurrence",
    deepLink: "Relevant authorised resource",
    sensitiveContent: "Minimal context; no secrets or unauthorised details",
    auditRelation: "As applicable",
  },
  {
    id: "PD-11",
    name: "PROJECT_REVIEW_ACTION_REQUIRED",
    family: "projects_delivery",
    classification: "NOTIFY",
    trigger: "Concrete review action is required.",
    recipients: "Assigned Reviewer only.",
    permissionScope: "Effective permission/scope/assignment as specified",
    environment: "Where relevant",
    clientFacing: "No unless explicitly stated",
    actionType: "ACTION_REQUIRED",
    priority: "P2",
    priorityFloor: "P2",
    inApp: true,
    emailDelivery: "IMMEDIATE",
    quietHours: "RESPECT",
    digest: "NO",
    escalation: "None unless explicitly stated",
    resolution: "Review action completed/reassigned/superseded.",
    deduplication: "Event ID + resource + recipient + lifecycle occurrence",
    deepLink: "Relevant authorised resource",
    sensitiveContent: "Minimal context; no secrets or unauthorised details",
    auditRelation: "As applicable",
  },
  {
    id: "PD-12",
    name: "PROJECT_BLOCKER_CREATED",
    family: "projects_delivery",
    classification: "NOTIFY",
    trigger: "Material blocker exists that prevents or threatens delivery.",
    recipients: "Responsible assignee; relevant Project/Delivery oversight.",
    permissionScope: "Effective permission/scope/assignment as specified",
    environment: "Where relevant",
    clientFacing: "No unless explicitly stated",
    actionType: "ACTION_REQUIRED",
    priority: "P2; P1 only if business-critical",
    priorityFloor: "P1",
    inApp: true,
    emailDelivery: "IMMEDIATE",
    quietHours: "P1 BYPASS; otherwise RESPECT",
    digest: "NO",
    escalation: "If unresolved at configured blocker escalation threshold or threatens Project deadline, escalate to higher delivery oversight/Super Admin as authorised.",
    resolution: "Blocker marked resolved or superseded.",
    deduplication: "Event ID + resource + recipient + lifecycle occurrence",
    deepLink: "Relevant authorised resource",
    sensitiveContent: "Minimal context; no secrets or unauthorised details",
    auditRelation: "As applicable",
  },
  {
    id: "PD-13",
    name: "PROJECT_BLOCKER_RESOLVED",
    family: "projects_delivery",
    classification: "NOTIFY",
    trigger: "Active material blocker is resolved.",
    recipients: "Users whose next action/dependency changes because of resolution.",
    permissionScope: "Effective permission/scope/assignment as specified",
    environment: "Where relevant",
    clientFacing: "No unless explicitly stated",
    actionType: "RESOLUTION_NOTICE",
    priority: "P3",
    priorityFloor: "P3",
    inApp: true,
    emailDelivery: "OPTIONAL",
    quietHours: "RESPECT",
    digest: "YES if non-urgent",
    escalation: "None unless explicitly stated",
    resolution: "Resolution notice is informational; related blocker notification must clear.",
    deduplication: "Event ID + resource + recipient + lifecycle occurrence",
    deepLink: "Relevant authorised resource",
    sensitiveContent: "Minimal context; no secrets or unauthorised details",
    auditRelation: "As applicable",
    implementationNotes: "Related blocker notification must no longer appear unresolved.",
  },
  {
    id: "PD-14",
    name: "PROJECT_DEPENDENCY_ACTION_REQUIRED",
    family: "projects_delivery",
    classification: "NOTIFY",
    trigger: "External/internal dependency requires concrete action.",
    recipients: "Assigned dependency owner + relevant Project oversight.",
    permissionScope: "Effective permission/scope/assignment as specified",
    environment: "Where relevant",
    clientFacing: "No unless explicitly stated",
    actionType: "ACTION_REQUIRED",
    priority: "P2/P3",
    priorityFloor: "P2",
    inApp: true,
    emailDelivery: "IMMEDIATE where delivery is affected",
    quietHours: "RESPECT",
    digest: "NO",
    escalation: "None unless explicitly stated",
    resolution: "Dependency satisfied, cancelled or superseded.",
    deduplication: "Event ID + resource + recipient + lifecycle occurrence",
    deepLink: "Relevant authorised resource",
    sensitiveContent: "Minimal context; no secrets or unauthorised details",
    auditRelation: "As applicable",
  },
  {
    id: "PD-15",
    name: "PROJECT_CLIENT_INFORMATION_REQUIRED",
    family: "projects_delivery",
    classification: "NOTIFY",
    trigger: "Project requires information/documentation from Client.",
    recipients: "Correct Client; assigned Project responsible user.",
    permissionScope: "Effective permission/scope/assignment as specified",
    environment: "Where relevant",
    clientFacing: "Yes.",
    actionType: "ACTION_REQUIRED",
    priority: "P2/P3",
    priorityFloor: "P2",
    inApp: true,
    emailDelivery: "IMMEDIATE to Client",
    quietHours: "RESPECT",
    digest: "NO",
    escalation: "None unless explicitly stated",
    resolution: "Information received or request cancelled/superseded.",
    deduplication: "Event ID + resource + recipient + lifecycle occurrence",
    deepLink: "Relevant authorised resource",
    sensitiveContent: "Minimal context; no secrets or unauthorised details",
    auditRelation: "As applicable",
  },
  {
    id: "PD-16",
    name: "PROJECT_CLIENT_INFORMATION_RECEIVED",
    family: "projects_delivery",
    classification: "NOTIFY",
    trigger: "Client provides requested Project information/documentation.",
    recipients: "Current assigned internal responsible user.",
    permissionScope: "Effective permission/scope/assignment as specified",
    environment: "Where relevant",
    clientFacing: "No unless explicitly stated",
    actionType: "AWARENESS / ACTION_REQUIRED",
    priority: "P3",
    priorityFloor: "P3",
    inApp: true,
    emailDelivery: "OPTIONAL; IMMEDIATE where work was blocked",
    quietHours: "RESPECT",
    digest: "YES only if no immediate action is required",
    escalation: "None unless explicitly stated",
    resolution: "Underlying Project work progresses.",
    deduplication: "Event ID + resource + recipient + lifecycle occurrence",
    deepLink: "Relevant authorised resource",
    sensitiveContent: "Minimal context; no secrets or unauthorised details",
    auditRelation: "As applicable",
  },
  {
    id: "PD-17",
    name: "PROJECT_DELIVERY_STATE_CHANGED",
    family: "projects_delivery",
    classification: "NOTIFY",
    trigger: "Material delivery lifecycle transition such as ready for review, approved, delivery ready, delivered, or paused where attention is required.",
    recipients: "Only authorised stakeholders affected by the transition.",
    permissionScope: "Effective permission/scope/assignment as specified",
    environment: "Where relevant",
    clientFacing: "No unless explicitly stated",
    actionType: "AWARENESS / ACTION_REQUIRED depending on state",
    priority: "P3 or P2",
    priorityFloor: "P2",
    inApp: true,
    emailDelivery: "Context dependent",
    quietHours: "RESPECT",
    digest: "YES only for non-urgent informational transitions",
    escalation: "None unless explicitly stated",
    resolution: "Superseded by next authoritative delivery state.",
    deduplication: "Event ID + resource + recipient + lifecycle occurrence",
    deepLink: "Relevant authorised resource",
    sensitiveContent: "Minimal context; no secrets or unauthorised details",
    auditRelation: "As applicable",
  },

  // ---- Family 5 — Payments & Billing (8 events) ----
  {
    id: "PB-01",
    name: "INVOICE_CREATED_ACTION_REQUIRED",
    family: "payments_billing",
    classification: "NOTIFY",
    trigger: "Invoice creation requires human attention.",
    recipients: "Authorised Billing user.",
    permissionScope: "Effective permission/scope/assignment as specified",
    environment: "Where relevant",
    clientFacing: "No unless explicitly stated",
    actionType: "ACTION_REQUIRED",
    priority: "P3",
    priorityFloor: "P3",
    inApp: true,
    emailDelivery: "OPTIONAL",
    quietHours: "RESPECT",
    digest: "YES",
    escalation: "None unless explicitly stated",
    resolution: "Invoice issue/action resolved.",
    deduplication: "Event ID + resource + recipient + lifecycle occurrence",
    deepLink: "Relevant authorised resource",
    sensitiveContent: "Minimal context; no secrets or unauthorised details",
    auditRelation: "As applicable",
    implementationNotes: "Routine successful automated invoice generation does not need a Notification Center event.",
  },
  {
    id: "PB-02",
    name: "PAYMENT_DUE_7D",
    family: "payments_billing",
    classification: "NOTIFY",
    trigger: "Invoice remains unpaid seven days before due date.",
    recipients: "Correct Client billing recipient; authorised internal Billing responsible user where operationally relevant.",
    permissionScope: "Effective permission/scope/assignment as specified",
    environment: "Where relevant",
    clientFacing: "Yes.",
    actionType: "PREPARATION_REQUIRED",
    priority: "P3",
    priorityFloor: "P3",
    inApp: true,
    emailDelivery: "IMMEDIATE",
    quietHours: "RESPECT",
    digest: "NO",
    escalation: "None unless explicitly stated",
    resolution: "Payment completed, invoice cancelled or superseded.",
    deduplication: "Invoice ID + due-date version + 7D + recipient",
    deepLink: "Relevant authorised resource",
    sensitiveContent: "Minimal context; no secrets or unauthorised details",
    auditRelation: "As applicable",
  },
  {
    id: "PB-03",
    name: "PAYMENT_DUE_1D",
    family: "payments_billing",
    classification: "NOTIFY",
    trigger: "Invoice remains unpaid one day before due date.",
    recipients: "Correct Client billing recipient + authorised Billing responsible user as appropriate.",
    permissionScope: "Effective permission/scope/assignment as specified",
    environment: "Where relevant",
    clientFacing: "Yes.",
    actionType: "ACTION_REQUIRED",
    priority: "P2/P3",
    priorityFloor: "P2",
    inApp: true,
    emailDelivery: "IMMEDIATE",
    quietHours: "RESPECT",
    digest: "NO",
    escalation: "None unless explicitly stated",
    resolution: "Payment completed, invoice cancelled or superseded.",
    deduplication: "Invoice ID + due-date version + 1D + recipient",
    deepLink: "Relevant authorised resource",
    sensitiveContent: "Minimal context; no secrets or unauthorised details",
    auditRelation: "As applicable",
  },
  {
    id: "PB-04",
    name: "PAYMENT_DUE_TODAY",
    family: "payments_billing",
    classification: "NOTIFY",
    trigger: "Invoice remains unpaid on due date.",
    recipients: "Correct Client billing recipient + authorised Billing responsible user.",
    permissionScope: "Effective permission/scope/assignment as specified",
    environment: "Where relevant",
    clientFacing: "Yes.",
    actionType: "ACTION_REQUIRED",
    priority: "P2",
    priorityFloor: "P2",
    inApp: true,
    emailDelivery: "IMMEDIATE",
    quietHours: "RESPECT",
    digest: "NO",
    escalation: "None unless explicitly stated",
    resolution: "Payment completed, invoice cancelled or superseded.",
    deduplication: "Invoice ID + due-date version + DUE + recipient",
    deepLink: "Relevant authorised resource",
    sensitiveContent: "Minimal context; no secrets or unauthorised details",
    auditRelation: "As applicable",
  },
  {
    id: "PB-05",
    name: "PAYMENT_OVERDUE",
    family: "payments_billing",
    classification: "NOTIFY",
    trigger: "Invoice remains unpaid after due date.",
    recipients: "Client billing recipient; authorised internal Billing responsible user.",
    permissionScope: "Effective permission/scope/assignment as specified",
    environment: "Where relevant",
    clientFacing: "Yes.",
    actionType: "ACTION_REQUIRED",
    priority: "P2",
    priorityFloor: "P2",
    inApp: true,
    emailDelivery: "IMMEDIATE",
    quietHours: "RESPECT",
    digest: "NO",
    escalation: "Further commercial/legal action is outside this catalogue and must follow approved IO SKY contractual/legal rules.",
    resolution: "Payment completed, invoice legally/operationally superseded or authorised closure.",
    deduplication: "Event ID + resource + recipient + lifecycle occurrence",
    deepLink: "Relevant authorised resource",
    sensitiveContent: "Minimal context; no secrets or unauthorised details",
    auditRelation: "As applicable",
  },
  {
    id: "PB-06",
    name: "PAYMENT_FAILED",
    family: "payments_billing",
    classification: "NOTIFY",
    trigger: "Payment attempt fails and human action is required.",
    recipients: "Correct Client; authorised Billing responsible user.",
    permissionScope: "Effective permission/scope/assignment as specified",
    environment: "Where relevant",
    clientFacing: "Yes.",
    actionType: "ACTION_REQUIRED",
    priority: "P2",
    priorityFloor: "P2",
    inApp: true,
    emailDelivery: "IMMEDIATE",
    quietHours: "RESPECT",
    digest: "NO",
    escalation: "None unless explicitly stated",
    resolution: "Successful payment or authorised alternative resolution.",
    deduplication: "Event ID + resource + recipient + lifecycle occurrence",
    deepLink: "Relevant authorised resource",
    sensitiveContent: "Do not expose sensitive processor/security details.",
    auditRelation: "As applicable",
  },
  {
    id: "PB-07",
    name: "PAYMENT_COMPLETED",
    family: "payments_billing",
    classification: "NOTIFY",
    trigger: "Payment successfully completed.",
    recipients: "Client confirmation; relevant Billing user where operationally useful.",
    permissionScope: "Effective permission/scope/assignment as specified",
    environment: "Where relevant",
    clientFacing: "Yes as appropriate.",
    actionType: "AWARENESS",
    priority: "P4/P3",
    priorityFloor: "P3",
    inApp: true,
    emailDelivery: "Client receipt/transactional as applicable; internal OPTIONAL",
    quietHours: "RESPECT",
    digest: "YES internally",
    escalation: "None unless explicitly stated",
    resolution: "Informational.",
    deduplication: "Event ID + resource + recipient + lifecycle occurrence",
    deepLink: "Relevant authorised resource",
    sensitiveContent: "Minimal context; no secrets or unauthorised details",
    auditRelation: "As applicable",
    implementationNotes: "Generate Notification Center event only where completion is operationally meaningful. Payment state itself must always update.",
  },
  {
    id: "PB-08",
    name: "BILLING_ACTION_REQUIRED",
    family: "payments_billing",
    classification: "NOTIFY",
    trigger: "A real Billing action exists and no more specific event applies.",
    recipients: "Authorised Billing responsible user and/or correct Client where underlying action requires.",
    permissionScope: "Effective permission/scope/assignment as specified",
    environment: "Where relevant",
    clientFacing: "No unless explicitly stated",
    actionType: "ACTION_REQUIRED",
    priority: "P2/P3",
    priorityFloor: "P2",
    inApp: true,
    emailDelivery: "IMMEDIATE where time-sensitive",
    quietHours: "RESPECT",
    digest: "NO",
    escalation: "None unless explicitly stated",
    resolution: "Underlying action completed/cancelled/superseded.",
    deduplication: "Event ID + resource + recipient + lifecycle occurrence",
    deepLink: "Relevant authorised resource",
    sensitiveContent: "Minimal context; no secrets or unauthorised details",
    auditRelation: "As applicable",
    implementationNotes: "Strict fallback only.",
  },

  // ---- Family 6 — AI Operations (6 events) ----
  {
    id: "AO-01",
    name: "AI_OPERATION_FAILED",
    family: "ai_operations",
    classification: "NOTIFY",
    trigger: "AI process cannot continue successfully without intervention.",
    recipients: "Authorised assigned AI/technical responsible users.",
    permissionScope: "Effective permission/scope/assignment as specified",
    environment: "Where relevant",
    clientFacing: "No unless explicitly stated",
    actionType: "ACTION_REQUIRED",
    priority: "P2/P1 depending on impact",
    priorityFloor: "P1",
    inApp: true,
    emailDelivery: "IMMEDIATE",
    quietHours: "P1 BYPASS; P2 RESPECT",
    digest: "NO",
    escalation: "None unless explicitly stated",
    resolution: "Process successfully recovered/restarted or intentionally terminated.",
    deduplication: "Event ID + resource + recipient + lifecycle occurrence",
    deepLink: "Relevant authorised resource",
    sensitiveContent: "Minimal context; no secrets or unauthorised details",
    auditRelation: "As applicable",
  },
  {
    id: "AO-02",
    name: "AI_HUMAN_INTERVENTION_REQUIRED",
    family: "ai_operations",
    classification: "NOTIFY",
    trigger: "AI workflow explicitly requires authorised human decision/action.",
    recipients: "Assigned authorised responsible user.",
    permissionScope: "Effective permission/scope/assignment as specified",
    environment: "Where relevant",
    clientFacing: "No unless explicitly stated",
    actionType: "ACTION_REQUIRED",
    priority: "P2",
    priorityFloor: "P2",
    inApp: true,
    emailDelivery: "IMMEDIATE",
    quietHours: "RESPECT",
    digest: "NO",
    escalation: "None unless explicitly stated",
    resolution: "Human intervention completed or workflow superseded.",
    deduplication: "Event ID + resource + recipient + lifecycle occurrence",
    deepLink: "Relevant authorised resource",
    sensitiveContent: "Minimal context; no secrets or unauthorised details",
    auditRelation: "As applicable",
  },
  {
    id: "AO-03",
    name: "AI_PROCESSING_EXCEPTION",
    family: "ai_operations",
    classification: "NOTIFY",
    trigger: "Material AI processing exception requires investigation.",
    recipients: "Assigned operational/technical responsible users.",
    permissionScope: "Effective permission/scope/assignment as specified",
    environment: "Where relevant",
    clientFacing: "No unless explicitly stated",
    actionType: "ACTION_REQUIRED",
    priority: "P2",
    priorityFloor: "P2",
    inApp: true,
    emailDelivery: "IMMEDIATE",
    quietHours: "RESPECT",
    digest: "NO",
    escalation: "None unless explicitly stated",
    resolution: "Exception resolved/recovered/superseded.",
    deduplication: "Event ID + resource + recipient + lifecycle occurrence",
    deepLink: "Relevant authorised resource",
    sensitiveContent: "Minimal context; no secrets or unauthorised details",
    auditRelation: "As applicable",
    implementationNotes: "Repeated backend retries of the same exception must not flood the Notification Center.",
  },
  {
    id: "AO-04",
    name: "AI_OPERATION_THRESHOLD_EXCEEDED",
    family: "ai_operations",
    classification: "NOTIFY",
    trigger: "Explicitly approved actionable AI operational threshold is exceeded.",
    recipients: "Authorised responsible user(s).",
    permissionScope: "Effective permission/scope/assignment as specified",
    environment: "Where relevant",
    clientFacing: "No unless explicitly stated",
    actionType: "ACTION_REQUIRED",
    priority: "P2/P3 depending on threshold",
    priorityFloor: "P2",
    inApp: true,
    emailDelivery: "IMMEDIATE where action required",
    quietHours: "RESPECT",
    digest: "NO if action required",
    escalation: "None unless explicitly stated",
    resolution: "Threshold returns to acceptable state or authorised resolution.",
    deduplication: "Event ID + resource + recipient + lifecycle occurrence",
    deepLink: "Relevant authorised resource",
    sensitiveContent: "Minimal context; no secrets or unauthorised details",
    auditRelation: "As applicable",
    implementationNotes: "Thresholds must be explicitly configured rather than inferred.",
  },
  {
    id: "AO-05",
    name: "AI_SERVICE_UNAVAILABLE",
    family: "ai_operations",
    classification: "NOTIFY",
    trigger: "Required AI service/provider becomes unavailable with material platform impact.",
    recipients: "Assigned authorised operational/technical users + Super Admin for material outage.",
    permissionScope: "Effective permission/scope/assignment as specified",
    environment: "Where relevant",
    clientFacing: "No unless explicitly stated",
    actionType: "ACTION_REQUIRED",
    priority: "P1/P2",
    priorityFloor: "P1",
    inApp: true,
    emailDelivery: "IMMEDIATE",
    quietHours: "P1 BYPASS; P2 RESPECT",
    digest: "NO",
    escalation: "None unless explicitly stated",
    resolution: "Service restored or authorised workaround/closure.",
    deduplication: "Event ID + resource + recipient + lifecycle occurrence",
    deepLink: "Relevant authorised resource",
    sensitiveContent: "Minimal context; no secrets or unauthorised details",
    auditRelation: "As applicable",
  },
  {
    id: "AO-06",
    name: "AI_OPERATION_RECOVERED",
    family: "ai_operations",
    classification: "NOTIFY",
    trigger: "Previously material AI incident recovers.",
    recipients: "Users actively affected/responsible.",
    permissionScope: "Effective permission/scope/assignment as specified",
    environment: "Where relevant",
    clientFacing: "No unless explicitly stated",
    actionType: "RESOLUTION_NOTICE",
    priority: "P3",
    priorityFloor: "P3",
    inApp: true,
    emailDelivery: "OPTIONAL",
    quietHours: "RESPECT",
    digest: "YES where no immediate resumed action is required",
    escalation: "None unless explicitly stated",
    resolution: "Resolution notice is informational; prior incident attention clears.",
    deduplication: "Event ID + resource + recipient + lifecycle occurrence",
    deepLink: "Relevant authorised resource",
    sensitiveContent: "Minimal context; no secrets or unauthorised details",
    auditRelation: "As applicable",
  },

  // ---- Family 7 — Platform & Integrations (8 events) ----
  {
    id: "PI-01",
    name: "INTEGRATION_DISCONNECTED",
    family: "platform_integrations",
    classification: "NOTIFY",
    trigger: "Required integration loses working connection.",
    recipients: "Authorised owner/operator of affected integration.",
    permissionScope: "Effective permission/scope/assignment as specified",
    environment: "Where relevant",
    clientFacing: "No unless explicitly stated",
    actionType: "ACTION_REQUIRED",
    priority: "P2",
    priorityFloor: "P2",
    inApp: true,
    emailDelivery: "IMMEDIATE",
    quietHours: "RESPECT unless critical Production impact",
    digest: "NO",
    escalation: "None unless explicitly stated",
    resolution: "Integration restored or intentionally disconnected.",
    deduplication: "Event ID + resource + recipient + lifecycle occurrence",
    deepLink: "Relevant authorised resource",
    sensitiveContent: "Minimal context; no secrets or unauthorised details",
    auditRelation: "As applicable",
  },
  {
    id: "PI-02",
    name: "INTEGRATION_AUTH_EXPIRED",
    family: "platform_integrations",
    classification: "NOTIFY",
    trigger: "Integration authentication/authorization expires and human action is required.",
    recipients: "Authorised integration owner/operator.",
    permissionScope: "Effective permission/scope/assignment as specified",
    environment: "Where relevant",
    clientFacing: "No unless explicitly stated",
    actionType: "ACTION_REQUIRED",
    priority: "P2",
    priorityFloor: "P2",
    inApp: true,
    emailDelivery: "IMMEDIATE",
    quietHours: "RESPECT",
    digest: "NO",
    escalation: "None unless explicitly stated",
    resolution: "Authentication restored or integration intentionally disabled.",
    deduplication: "Event ID + resource + recipient + lifecycle occurrence",
    deepLink: "Relevant authorised resource",
    sensitiveContent: "Minimal context; no secrets or unauthorised details",
    auditRelation: "As applicable",
  },
  {
    id: "PI-03",
    name: "INTEGRATION_FAILURE",
    family: "platform_integrations",
    classification: "NOTIFY",
    trigger: "Integration fails materially and operation is affected.",
    recipients: "Appropriate authorised technical/operational owner.",
    permissionScope: "Effective permission/scope/assignment as specified",
    environment: "Where relevant",
    clientFacing: "No unless explicitly stated",
    actionType: "ACTION_REQUIRED",
    priority: "P2/P1",
    priorityFloor: "P1",
    inApp: true,
    emailDelivery: "IMMEDIATE",
    quietHours: "P1 BYPASS; otherwise RESPECT",
    digest: "NO",
    escalation: "None unless explicitly stated",
    resolution: "Integration recovers or issue is resolved.",
    deduplication: "Event ID + resource + recipient + lifecycle occurrence",
    deepLink: "Relevant authorised resource",
    sensitiveContent: "Minimal context; no secrets or unauthorised details",
    auditRelation: "As applicable",
  },
  {
    id: "PI-04",
    name: "EXTERNAL_SERVICE_UNAVAILABLE",
    family: "platform_integrations",
    classification: "NOTIFY",
    trigger: "External service outage materially impacts platform capability.",
    recipients: "Authorised responsible technical/operational users.",
    permissionScope: "Effective permission/scope/assignment as specified",
    environment: "Where relevant",
    clientFacing: "No unless explicitly stated",
    actionType: "ACTION_REQUIRED",
    priority: "Impact-based P1/P2/P3",
    priorityFloor: "P1",
    inApp: true,
    emailDelivery: "IMMEDIATE for P1/P2",
    quietHours: "P1 BYPASS; otherwise RESPECT",
    digest: "NO when impact is active",
    escalation: "None unless explicitly stated",
    resolution: "Service recovers or authorised workaround/closure.",
    deduplication: "Event ID + resource + recipient + lifecycle occurrence",
    deepLink: "Relevant authorised resource",
    sensitiveContent: "Minimal context; no secrets or unauthorised details",
    auditRelation: "As applicable",
  },
  {
    id: "PI-05",
    name: "PLATFORM_COMPONENT_ACTION_REQUIRED",
    family: "platform_integrations",
    classification: "NOTIFY",
    trigger: "Platform component requires authorised intervention.",
    recipients: "Authorised component owner/operator.",
    permissionScope: "Effective permission/scope/assignment as specified",
    environment: "Where relevant",
    clientFacing: "No unless explicitly stated",
    actionType: "ACTION_REQUIRED",
    priority: "P2",
    priorityFloor: "P2",
    inApp: true,
    emailDelivery: "IMMEDIATE",
    quietHours: "RESPECT unless separately P1",
    digest: "NO",
    escalation: "None unless explicitly stated",
    resolution: "Required intervention completed or issue superseded.",
    deduplication: "Event ID + resource + recipient + lifecycle occurrence",
    deepLink: "Relevant authorised resource",
    sensitiveContent: "Minimal context; no secrets or unauthorised details",
    auditRelation: "As applicable",
  },
  {
    id: "PI-06",
    name: "PLATFORM_CONFIGURATION_ACTION_REQUIRED",
    family: "platform_integrations",
    classification: "NOTIFY",
    trigger: "Misconfiguration materially affects operation and requires action.",
    recipients: "Authorised responsible user.",
    permissionScope: "Effective permission/scope/assignment as specified",
    environment: "Where relevant",
    clientFacing: "No unless explicitly stated",
    actionType: "ACTION_REQUIRED",
    priority: "P2/P3",
    priorityFloor: "P2",
    inApp: true,
    emailDelivery: "IMMEDIATE where blocking",
    quietHours: "RESPECT",
    digest: "NO",
    escalation: "None unless explicitly stated",
    resolution: "Configuration corrected or issue superseded.",
    deduplication: "Event ID + resource + recipient + lifecycle occurrence",
    deepLink: "Relevant authorised resource",
    sensitiveContent: "Minimal context; no secrets or unauthorised details",
    auditRelation: "Ordinary successful configuration changes are Audit Only; privileged changes should be",
  },
  {
    id: "PI-07",
    name: "PLATFORM_INCIDENT_CRITICAL",
    family: "platform_integrations",
    classification: "NOTIFY",
    trigger: "Critical platform incident requires immediate intervention.",
    recipients: "Appropriate authorised technical responsible users; Super Admin.",
    permissionScope: "Effective permission/scope/assignment as specified",
    environment: "Where relevant",
    clientFacing: "No unless explicitly stated",
    actionType: "ACTION_REQUIRED",
    priority: "P1",
    priorityFloor: "P1",
    inApp: true,
    emailDelivery: "IMMEDIATE",
    quietHours: "BYPASS",
    digest: "NEVER",
    escalation: "Immediate according to authorised operational incident chain.",
    resolution: "Incident confirmed resolved.",
    deduplication: "Event ID + resource + recipient + lifecycle occurrence",
    deepLink: "Relevant authorised resource",
    sensitiveContent: "Minimal context; no secrets or unauthorised details",
    auditRelation: "As applicable",
  },
  {
    id: "PI-08",
    name: "PLATFORM_SERVICE_RECOVERED",
    family: "platform_integrations",
    classification: "NOTIFY",
    trigger: "Previously material outage is resolved.",
    recipients: "Affected responsible users.",
    permissionScope: "Effective permission/scope/assignment as specified",
    environment: "Where relevant",
    clientFacing: "No unless explicitly stated",
    actionType: "RESOLUTION_NOTICE",
    priority: "P3",
    priorityFloor: "P3",
    inApp: true,
    emailDelivery: "OPTIONAL / IMMEDIATE if teams were actively responding",
    quietHours: "RESPECT",
    digest: "YES where no immediate restart action is needed",
    escalation: "None unless explicitly stated",
    resolution: "Resolution notice informational; related incident attention clears.",
    deduplication: "Event ID + resource + recipient + lifecycle occurrence",
    deepLink: "Relevant authorised resource",
    sensitiveContent: "Minimal context; no secrets or unauthorised details",
    auditRelation: "As applicable",
  },

  // ---- Family 8 — Security & Access (10 events) ----
  {
    id: "SA-01",
    name: "SECURITY_ALERT_CRITICAL",
    family: "security_access",
    classification: "NOTIFY",
    trigger: "Confirmed critical security condition requires immediate human attention.",
    recipients: "Super Admin; explicitly authorised Security user(s).",
    permissionScope: "Effective permission/scope/assignment as specified",
    environment: "Where relevant",
    clientFacing: "No unless explicitly stated",
    actionType: "ACTION_REQUIRED",
    priority: "P1",
    priorityFloor: "P1",
    inApp: true,
    emailDelivery: "IMMEDIATE / MANDATORY",
    quietHours: "BYPASS",
    digest: "NEVER",
    escalation: "Immediate.",
    resolution: "Security incident formally resolved/closed.",
    deduplication: "Event ID + resource + recipient + lifecycle occurrence",
    deepLink: "Authorised Security Center record",
    sensitiveContent: "Minimal preview only; sensitive details remain in Security Center.",
    auditRelation: "Mandatory traceability.",
  },
  {
    id: "SA-02",
    name: "SECURITY_ACTION_REQUIRED",
    family: "security_access",
    classification: "NOTIFY",
    trigger: "Material security action is required but incident is not necessarily P1.",
    recipients: "Explicitly authorised Security user(s).",
    permissionScope: "Effective permission/scope/assignment as specified",
    environment: "Where relevant",
    clientFacing: "No unless explicitly stated",
    actionType: "ACTION_REQUIRED",
    priority: "P2",
    priorityFloor: "P2",
    inApp: true,
    emailDelivery: "IMMEDIATE",
    quietHours: "RESPECT unless severity escalates",
    digest: "NO",
    escalation: "None unless explicitly stated",
    resolution: "Security action completed or issue superseded.",
    deduplication: "Event ID + resource + recipient + lifecycle occurrence",
    deepLink: "Relevant authorised resource",
    sensitiveContent: "Minimal context; no secrets or unauthorised details",
    auditRelation: "As appropriate for security action.",
  },
  {
    id: "SA-03",
    name: "PRIVILEGED_ACCESS_GRANTED",
    family: "security_access",
    classification: "NOTIFY",
    trigger: "Privileged platform/security access is granted.",
    recipients: "Super Admin and authorised governance/security oversight where appropriate.",
    permissionScope: "Effective permission/scope/assignment as specified",
    environment: "Where relevant",
    clientFacing: "No unless explicitly stated",
    actionType: "AWARENESS / oversight",
    priority: "P2/P3",
    priorityFloor: "P2",
    inApp: true,
    emailDelivery: "IMMEDIATE for sensitive privilege",
    quietHours: "RESPECT",
    digest: "NO for high privilege",
    escalation: "None unless explicitly stated",
    resolution: "Informational/oversight state completed or superseded.",
    deduplication: "Event ID + resource + recipient + lifecycle occurrence",
    deepLink: "Relevant authorised resource",
    sensitiveContent: "Minimal context; no secrets or unauthorised details",
    auditRelation: "Mandatory traceability.",
  },
  {
    id: "SA-04",
    name: "PRIVILEGED_ACCESS_REVOKED",
    family: "security_access",
    classification: "NOTIFY",
    trigger: "Privileged access is revoked.",
    recipients: "Appropriate authorised oversight users.",
    permissionScope: "Effective permission/scope/assignment as specified",
    environment: "Where relevant",
    clientFacing: "No unless explicitly stated",
    actionType: "AWARENESS",
    priority: "P2/P3",
    priorityFloor: "P2",
    inApp: true,
    emailDelivery: "Context dependent",
    quietHours: "RESPECT",
    digest: "Context dependent",
    escalation: "None unless explicitly stated",
    resolution: "Informational.",
    deduplication: "Event ID + resource + recipient + lifecycle occurrence",
    deepLink: "Relevant authorised resource",
    sensitiveContent: "Minimal context; no secrets or unauthorised details",
    auditRelation: "Mandatory.",
    implementationNotes: "Existing stale notifications must not retain resource access.",
  },
  {
    id: "SA-05",
    name: "SIGNIFICANT_PERMISSION_CHANGE",
    family: "security_access",
    classification: "NOTIFY",
    trigger: "Material permission change warrants security/governance awareness.",
    recipients: "Authorised oversight.",
    permissionScope: "Effective permission/scope/assignment as specified",
    environment: "Where relevant",
    clientFacing: "No unless explicitly stated",
    actionType: "AWARENESS / ACTION_REQUIRED where review is needed",
    priority: "P2/P3",
    priorityFloor: "P2",
    inApp: true,
    emailDelivery: "IMMEDIATE where high privilege",
    quietHours: "RESPECT",
    digest: "Context dependent",
    escalation: "None unless explicitly stated",
    resolution: "Oversight completed or change superseded.",
    deduplication: "Event ID + resource + recipient + lifecycle occurrence",
    deepLink: "Relevant authorised resource",
    sensitiveContent: "Minimal context; no secrets or unauthorised details",
    auditRelation: "Mandatory.",
    implementationNotes: "Routine low-risk assignment changes do not belong here.",
  },
  {
    id: "SA-06",
    name: "SECURITY_CENTER_ACTION_REQUIRED",
    family: "security_access",
    classification: "NOTIFY",
    trigger: "Security Center record requires concrete authorised action.",
    recipients: "Only users with explicit Security Center authorization.",
    permissionScope: "Effective permission/scope/assignment as specified",
    environment: "Where relevant",
    clientFacing: "No unless explicitly stated",
    actionType: "ACTION_REQUIRED",
    priority: "P2",
    priorityFloor: "P2",
    inApp: true,
    emailDelivery: "IMMEDIATE",
    quietHours: "RESPECT unless escalated to P1",
    digest: "NO",
    escalation: "None unless explicitly stated",
    resolution: "Security Center action completed/resolved.",
    deduplication: "Event ID + resource + recipient + lifecycle occurrence",
    deepLink: "Relevant authorised resource",
    sensitiveContent: "Minimal context; no secrets or unauthorised details",
    auditRelation: "As applicable",
  },
  {
    id: "SA-07",
    name: "SECURITY_CONFIGURATION_ACTION_REQUIRED",
    family: "security_access",
    classification: "NOTIFY",
    trigger: "Security configuration requires intervention.",
    recipients: "Explicit Security-authorised users.",
    permissionScope: "Effective permission/scope/assignment as specified",
    environment: "Where relevant",
    clientFacing: "No unless explicitly stated",
    actionType: "ACTION_REQUIRED",
    priority: "P2",
    priorityFloor: "P2",
    inApp: true,
    emailDelivery: "IMMEDIATE",
    quietHours: "RESPECT",
    digest: "NO",
    escalation: "None unless explicitly stated",
    resolution: "Configuration corrected/resolved.",
    deduplication: "Event ID + resource + recipient + lifecycle occurrence",
    deepLink: "Relevant authorised resource",
    sensitiveContent: "Minimal context; no secrets or unauthorised details",
    auditRelation: "Privileged changes/resolution must be traceable.",
  },
  {
    id: "SA-08",
    name: "SUSPICIOUS_ACCESS_EVENT",
    family: "security_access",
    classification: "NOTIFY",
    trigger: "Security controls classify access activity as sufficiently suspicious to justify human attention.",
    recipients: "Explicit Security-authorised users; affected user only when appropriate user-facing security action is required.",
    permissionScope: "Effective permission/scope/assignment as specified",
    environment: "Where relevant",
    clientFacing: "No unless explicitly stated",
    actionType: "ACTION_REQUIRED",
    priority: "P1/P2",
    priorityFloor: "P1",
    inApp: true,
    emailDelivery: "IMMEDIATE",
    quietHours: "P1 BYPASS; P2 RESPECT",
    digest: "NO",
    escalation: "None unless explicitly stated",
    resolution: "Investigation/action resolved or event dismissed by authorised workflow.",
    deduplication: "Event ID + resource + recipient + lifecycle occurrence",
    deepLink: "Relevant authorised resource",
    sensitiveContent: "Minimal safe information; no unnecessary exploit or credential details.",
    auditRelation: "As applicable",
    implementationNotes: "Ordinary successful login does not automatically generate this event.",
  },
  {
    id: "SA-09",
    name: "ACCOUNT_SECURITY_ACTION_REQUIRED",
    family: "security_access",
    classification: "NOTIFY",
    trigger: "Specific user must perform a security action.",
    recipients: "Affected authorised account holder.",
    permissionScope: "Effective permission/scope/assignment as specified",
    environment: "Where relevant",
    clientFacing: "May be Client-facing when the affected account is a Client.",
    actionType: "ACTION_REQUIRED",
    priority: "P1/P2",
    priorityFloor: "P1",
    inApp: true,
    emailDelivery: "IMMEDIATE",
    quietHours: "P1 BYPASS; P2 RESPECT",
    digest: "NO",
    escalation: "None unless explicitly stated",
    resolution: "Required account security action completed or authorised resolution.",
    deduplication: "Event ID + resource + recipient + lifecycle occurrence",
    deepLink: "Relevant authorised resource",
    sensitiveContent: "Minimal safe information.",
    auditRelation: "As applicable",
  },
  {
    id: "SA-10",
    name: "SECURITY_INCIDENT_RESOLVED",
    family: "security_access",
    classification: "NOTIFY",
    trigger: "Active security incident is formally resolved.",
    recipients: "Authorised stakeholders who were responsible/affected.",
    permissionScope: "Effective permission/scope/assignment as specified",
    environment: "Where relevant",
    clientFacing: "No unless explicitly stated",
    actionType: "RESOLUTION_NOTICE",
    priority: "P3",
    priorityFloor: "P3",
    inApp: true,
    emailDelivery: "IMMEDIATE where incident response was active",
    quietHours: "RESPECT",
    digest: "YES if non-urgent",
    escalation: "None unless explicitly stated",
    resolution: "Resolution notice informational; prior unresolved security attention clears.",
    deduplication: "Event ID + resource + recipient + lifecycle occurrence",
    deepLink: "Relevant authorised resource",
    sensitiveContent: "Minimal context; no secrets or unauthorised details",
    auditRelation: "As applicable",
  },

  // ---- Family 9 — Governance / System (6 events) ----
  {
    id: "GS-01",
    name: "GOVERNANCE_ACTION_REQUIRED",
    family: "governance_system",
    classification: "NOTIFY",
    trigger: "Material governance decision/action is required.",
    recipients: "Super Admin; explicitly authorised governance user if such responsibility is delegated.",
    permissionScope: "Effective permission/scope/assignment as specified",
    environment: "Where relevant",
    clientFacing: "No unless explicitly stated",
    actionType: "ACTION_REQUIRED",
    priority: "P2",
    priorityFloor: "P2",
    inApp: true,
    emailDelivery: "IMMEDIATE",
    quietHours: "RESPECT unless event becomes critical",
    digest: "NO",
    escalation: "None unless explicitly stated",
    resolution: "Governance action completed/cancelled/superseded.",
    deduplication: "Event ID + resource + recipient + lifecycle occurrence",
    deepLink: "Relevant authorised resource",
    sensitiveContent: "Minimal context; no secrets or unauthorised details",
    auditRelation: "As applicable",
  },
  {
    id: "GS-02",
    name: "PRIVILEGED_ACCESS_OVERSIGHT_REQUIRED",
    family: "governance_system",
    classification: "NOTIFY",
    trigger: "Privileged access state requires governance review/decision.",
    recipients: "Super Admin / authorised governance oversight.",
    permissionScope: "Effective permission/scope/assignment as specified",
    environment: "Where relevant",
    clientFacing: "No unless explicitly stated",
    actionType: "ACTION_REQUIRED",
    priority: "P2",
    priorityFloor: "P2",
    inApp: true,
    emailDelivery: "IMMEDIATE",
    quietHours: "RESPECT",
    digest: "NO",
    escalation: "None unless explicitly stated",
    resolution: "Oversight decision completed or state superseded.",
    deduplication: "Event ID + resource + recipient + lifecycle occurrence",
    deepLink: "Relevant authorised resource",
    sensitiveContent: "Minimal context; no secrets or unauthorised details",
    auditRelation: "Required where privileged action exists.",
  },
  {
    id: "GS-03",
    name: "ADMINISTRATIVE_CONFIGURATION_OVERSIGHT_REQUIRED",
    family: "governance_system",
    classification: "NOTIFY",
    trigger: "Significant administrative configuration requires oversight.",
    recipients: "Super Admin / authorised governance user.",
    permissionScope: "Effective permission/scope/assignment as specified",
    environment: "Where relevant",
    clientFacing: "No unless explicitly stated",
    actionType: "AWARENESS / ACTION_REQUIRED",
    priority: "P2/P3",
    priorityFloor: "P2",
    inApp: true,
    emailDelivery: "Context dependent",
    quietHours: "RESPECT",
    digest: "YES for non-urgent oversight",
    escalation: "None unless explicitly stated",
    resolution: "Oversight completed or configuration superseded.",
    deduplication: "Event ID + resource + recipient + lifecycle occurrence",
    deepLink: "Relevant authorised resource",
    sensitiveContent: "Minimal context; no secrets or unauthorised details",
    auditRelation: "As applicable",
    implementationNotes: "Routine administration belongs in Audit Log, not Notification Center.",
  },
  {
    id: "GS-04",
    name: "SYSTEM_GOVERNANCE_ISSUE",
    family: "governance_system",
    classification: "NOTIFY",
    trigger: "Material platform-level governance issue requires action.",
    recipients: "Super Admin + specifically authorised responsible users.",
    permissionScope: "Effective permission/scope/assignment as specified",
    environment: "Where relevant",
    clientFacing: "No unless explicitly stated",
    actionType: "ACTION_REQUIRED",
    priority: "P2/P1 depending on impact",
    priorityFloor: "P1",
    inApp: true,
    emailDelivery: "IMMEDIATE",
    quietHours: "P1 BYPASS; otherwise RESPECT",
    digest: "NO",
    escalation: "None unless explicitly stated",
    resolution: "Issue formally resolved/closed.",
    deduplication: "Event ID + resource + recipient + lifecycle occurrence",
    deepLink: "Relevant authorised resource",
    sensitiveContent: "Minimal context; no secrets or unauthorised details",
    auditRelation: "As applicable",
  },
  {
    id: "GS-05",
    name: "AUDIT_INTEGRITY_ACTION_REQUIRED",
    family: "governance_system",
    classification: "NOTIFY",
    trigger: "Audit integrity/tamper-evidence control reports a material state requiring authorised attention.",
    recipients: "Super Admin + appropriate authorised security/governance user.",
    permissionScope: "Effective permission/scope/assignment as specified",
    environment: "Where relevant",
    clientFacing: "No unless explicitly stated",
    actionType: "ACTION_REQUIRED",
    priority: "P1/P2",
    priorityFloor: "P1",
    inApp: true,
    emailDelivery: "IMMEDIATE",
    quietHours: "P1 BYPASS; P2 RESPECT",
    digest: "NO",
    escalation: "None unless explicitly stated",
    resolution: "Audit integrity issue resolved or authorised exception closed.",
    deduplication: "Event ID + resource + recipient + lifecycle occurrence",
    deepLink: "Relevant authorised resource",
    sensitiveContent: "Minimal context; no secrets or unauthorised details",
    auditRelation: "This event itself must be traceable.",
    implementationNotes: "This event does not define IO SKY's separate final Audit Log integrity architecture.",
  },
  {
    id: "GS-06",
    name: "GOVERNANCE_INCIDENT_RESOLVED",
    family: "governance_system",
    classification: "NOTIFY",
    trigger: "Governance/system issue is formally resolved.",
    recipients: "Authorised stakeholders.",
    permissionScope: "Effective permission/scope/assignment as specified",
    environment: "Where relevant",
    clientFacing: "No unless explicitly stated",
    actionType: "RESOLUTION_NOTICE",
    priority: "P3",
    priorityFloor: "P3",
    inApp: true,
    emailDelivery: "Context dependent",
    quietHours: "RESPECT",
    digest: "YES if non-urgent",
    escalation: "None unless explicitly stated",
    resolution: "Resolution notice informational; related actionable governance notification clears.",
    deduplication: "Event ID + resource + recipient + lifecycle occurrence",
    deepLink: "Relevant authorised resource",
    sensitiveContent: "Minimal context; no secrets or unauthorised details",
    auditRelation: "As applicable",
  },
] as const satisfies readonly NotificationEvent[];

export type NotificationEventId = (typeof NOTIFICATION_EVENTS)[number]["id"];
export type NotificationEventName = (typeof NOTIFICATION_EVENTS)[number]["name"];

const BY_ID = new Map<string, NotificationEvent>(
  NOTIFICATION_EVENTS.map((e) => [e.id, e as NotificationEvent]),
);
const BY_NAME = new Map<string, NotificationEvent>(
  NOTIFICATION_EVENTS.map((e) => [e.name, e as NotificationEvent]),
);

/** Look an event up by catalogue id, e.g. "AS-05". */
export function getNotificationEvent(id: string): NotificationEvent | undefined {
  return BY_ID.get(id);
}

/** Look an event up by machine name, e.g. "AI_SCAN_READY_FOR_REVIEW". */
export function getNotificationEventByName(name: string): NotificationEvent | undefined {
  return BY_NAME.get(name);
}

/** Every event belonging to one family. */
export function eventsInFamily(family: NotificationFamily): NotificationEvent[] {
  return NOTIFICATION_EVENTS.filter((e) => e.family === family) as NotificationEvent[];
}

/** Events the catalogue marks as requiring the recipient to act. */
export function actionRequiredEvents(): NotificationEvent[] {
  return NOTIFICATION_EVENTS.filter((e) =>
    e.actionType.toUpperCase().includes("ACTION_REQUIRED"),
  ) as NotificationEvent[];
}
